# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ParseSDK' do
pod 'Parse', '~> 1.7.1'
pod 'ParseUI', '~> 1.1.4'
end

target 'ParseSDKTests' do

end

target 'ParseSDKUITests' do

end

